# Generated by Django 5.0.7 on 2024-09-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='user_imagen',
            field=models.ImageField(upload_to='Avatares', verbose_name='image'),
        ),
    ]
