# Generated by Django 5.0.7 on 2024-10-06 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppMaquinas', '0002_alter_machine_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_spare_part', models.TextField(max_length=20, verbose_name='Nombre Repuesto')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('date_to_register', models.DateTimeField(auto_now_add=True)),
                ('date_to_out', models.DateField(auto_now=True)),
                ('available', models.BooleanField()),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código del Repuesto')),
                ('storage_location', models.CharField(max_length=100, verbose_name='Ubicación en Almacén')),
                ('minimum_stock', models.IntegerField(default=0, verbose_name='Stock Mínimo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('machine_is', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMaquinas.machine')),
            ],
        ),
    ]
