# Generated by Django 5.0.7 on 2024-10-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaquinas', '0002_alter_machine_photo'),
        ('AppRepuestos', '0002_alter_repuestos_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuestos',
            name='machine_is',
        ),
        migrations.AddField(
            model_name='repuestos',
            name='machines',
            field=models.ManyToManyField(related_name='repuestos', to='AppMaquinas.machine'),
        ),
    ]
