# Generated by Django 5.0.7 on 2024-11-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRepuestos', '0004_alter_repuestos_name_spare_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuestos',
            name='date_to_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
