# Generated by Django 5.0.7 on 2024-11-16 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaquinas', '0003_remove_machine_photo_machine_amperes_and_more'),
        ('AppRepuestos', '0005_alter_repuestos_date_to_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEntradasSalidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_spare_part', models.CharField(max_length=599, null=True)),
                ('out_spare_part', models.CharField(max_length=599, null=True)),
                ('machine_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMaquinas.machine', verbose_name='')),
                ('spare_part_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppRepuestos.repuestos', verbose_name='')),
            ],
        ),
    ]
