# Generated by Django 5.0.7 on 2024-11-18 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaquinas', '0003_remove_machine_photo_machine_amperes_and_more'),
        ('AppRepuestos', '0006_registroentradassalidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroentradassalidas',
            name='entry_spare_part',
            field=models.CharField(blank=True, max_length=599, null=True),
        ),
        migrations.RemoveField(
            model_name='registroentradassalidas',
            name='machine_relation',
        ),
        migrations.AlterField(
            model_name='registroentradassalidas',
            name='out_spare_part',
            field=models.CharField(blank=True, max_length=599, null=True),
        ),
        migrations.AlterField(
            model_name='registroentradassalidas',
            name='spare_part_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppRepuestos.repuestos', verbose_name=''),
        ),
        migrations.AddField(
            model_name='registroentradassalidas',
            name='machine_relation',
            field=models.ManyToManyField(related_name='maquina_registro', to='AppMaquinas.machine'),
        ),
    ]
