# Generated by Django 5.0.7 on 2024-11-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaquinas', '0003_remove_machine_photo_machine_amperes_and_more'),
        ('AppRepuestos', '0007_alter_registroentradassalidas_entry_spare_part_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroentradassalidas',
            name='entry_spare_part',
        ),
        migrations.RemoveField(
            model_name='registroentradassalidas',
            name='out_spare_part',
        ),
        migrations.AddField(
            model_name='registroentradassalidas',
            name='cantidad',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='registroentradassalidas',
            name='date_to_movent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='registroentradassalidas',
            name='tipo_movimiento',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registroentradassalidas',
            name='machine_relation',
            field=models.ManyToManyField(null=True, related_name='maquina_registro', to='AppMaquinas.machine'),
        ),
    ]
