# Generated by Django 5.0.7 on 2024-11-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaquinas', '0003_remove_machine_photo_machine_amperes_and_more'),
        ('AppRepuestos', '0008_remove_registroentradassalidas_entry_spare_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroentradassalidas',
            name='machine_relation',
            field=models.ManyToManyField(related_name='maquina_registro', to='AppMaquinas.machine'),
        ),
    ]
