# Generated by Django 5.0.7 on 2025-06-23 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRepuestos', '0010_registroentradassalidas_was_who_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroentradassalidas',
            name='entregado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_quien_recibe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroentradassalidas',
            name='prestado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroentradassalidas',
            name='se_uso',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
