# Generated by Django 5.0.7 on 2025-06-23 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRepuestos', '0011_registroentradassalidas_entregado_a_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroentradassalidas',
            name='devolucion_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_que_devuelve', to=settings.AUTH_USER_MODEL),
        ),
    ]
