# Generated by Django 5.0.7 on 2025-06-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRepuestos', '0012_registroentradassalidas_devolucion_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroentradassalidas',
            name='was_who',
        ),
        migrations.AddField(
            model_name='registroentradassalidas',
            name='devuelto',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
