# Generated by Django 5.0.7 on 2025-05-24 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHerramientas', '0002_tools_codigo_prestamoherramienta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamoherramienta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='prestamoherramienta',
            name='prestado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestado_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prestamoherramienta',
            name='prestado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tools',
            name='disponible',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='tools',
            name='codigo',
            field=models.CharField(max_length=31, null=True, unique=True),
        ),
    ]
