# Generated by Django 5.0.7 on 2025-05-28 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHerramientas', '0003_remove_prestamoherramienta_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamoherramienta',
            name='devolucion_recibida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devolucionador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prestamoherramienta',
            name='esta_devuelto',
            field=models.BooleanField(null=True),
        ),
    ]
