# Generated by Django 5.0.7 on 2024-10-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(max_length=500, verbose_name='descripcion')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Foto')),
            ],
        ),
    ]
