# Generated by Django 5.0.7 on 2024-10-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaquinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Maquinas', verbose_name='Foto'),
        ),
    ]
