# Generated by Django 5.0.7 on 2024-10-22 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaquinas', '0002_alter_machine_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='photo',
        ),
        migrations.AddField(
            model_name='machine',
            name='amperes',
            field=models.CharField(max_length=100, null=True, verbose_name='Amperios'),
        ),
        migrations.AddField(
            model_name='machine',
            name='capacity',
            field=models.CharField(max_length=100, null=True, verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='machine',
            name='fabricante',
            field=models.CharField(max_length=100, null=True, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='machine',
            name='power',
            field=models.CharField(max_length=100, null=True, verbose_name='Potencia'),
        ),
        migrations.AddField(
            model_name='machine',
            name='service',
            field=models.CharField(max_length=100, null=True, verbose_name='Servicios'),
        ),
        migrations.AddField(
            model_name='machine',
            name='site_room',
            field=models.CharField(max_length=100, null=True, verbose_name='Ubicacion'),
        ),
        migrations.AddField(
            model_name='machine',
            name='voltage',
            field=models.CharField(max_length=100, null=True, verbose_name='Voltaje'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='nombre'),
        ),
        migrations.CreateModel(
            name='MachineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_imagen', models.ImageField(upload_to='Maquinas', verbose_name='image')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_photos', to='AppMaquinas.machine')),
            ],
        ),
    ]
