# Generated by Django 5.0.7 on 2025-06-08 16:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInsumos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo_insumo', models.CharField(max_length=20, unique=True)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unidad_medida', models.CharField(choices=[('g', 'Gramos'), ('m', 'Metros'), ('und', 'Unidades')], max_length=50)),
                ('disponible', models.BooleanField(default=True)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('notas_insumo', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoInsumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ingreso', 'Ingreso'), ('prestamo', 'Préstamo'), ('devolucion', 'Devolución')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('esta_devuelto', models.BooleanField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('devolucion_recibida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='el_que_devuelve', to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppInsumos.insumos')),
                ('prestado_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='el_que_recibe', to=settings.AUTH_USER_MODEL)),
                ('prestado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='el_que_presta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de insumos',
                'verbose_name_plural': 'Registros de insumos',
            },
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
