# Generated by Django 5.0.7 on 2025-06-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInsumos', '0002_insumos_prestamoinsumos_delete_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamoinsumos',
            name='unidad_medida',
            field=models.CharField(choices=[('g', 'Gramos'), ('m', 'Metros'), ('und', 'Unidades'), ('L', 'Litros')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='unidad_medida',
            field=models.CharField(choices=[('g', 'Gramos'), ('m', 'Metros'), ('und', 'Unidades'), ('L', 'litros')], max_length=50),
        ),
    ]
